#!/usr/bin/env ruby
require_relative 'cellect_env'

class CellectStart
  include CellectEnv

  def initialize
    setup_puma_cmd
    setup_env_vars
  end

  def run
    if ENV['DEBUG_CELLECT_START']
      p @env_vars
      p @puma_cmd
    end
    exit system(@env_vars, @puma_cmd)
  end

  private

  def setup_puma_cmd
    @puma_cmd = "puma -b tcp://0.0.0.0:80 -t 8:16"
  end
end


CellectStart.new.run
